export const JEP_CATEGORY_COUNT = 6;
export const JEP_CLUES_PER_CATEGORY = 5;
export const JEP_FINAL_JEOPARDY_CATEGORY_COUNT = 1;
export const JEP_FINAL_JEOPARDY_CLUES_PER_CATEGORY = 1;
export const JEP_FINAL_JEOPARDY_MIN_MAX_WAGER_SIZE = 5;
