/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BingoState {
	connectionState: 'NOT_CONNECTED' | 'CONNECTING' | 'CONNECTED' | 'ERROR';
	players: {
		id: string;
		name: string;
		color: string;
		goalCount: number;
	}[];
	board: {
		id: string;
		goal: string;
		description?: string | null;
		completedByPlayers: string[];
	}[][];
}
