/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FeudState =
	| {
			state: 'WAITING_FOR_QUESTION' | 'WAITING_FOR_BUZZER';
	  }
	| {
			state: 'WAITING_FOR_FACEOFF_ANSWER';
			firstToBuzz: 'teamA' | 'teamB';
			teamInPlay: 'teamA' | 'teamB';
			anyGuessMadeBy: {
				teamA: boolean;
				teamB: boolean;
			};
	  }
	| {
			state: 'WAITING_FOR_PLAY_OR_PASS';
			faceoffWinner: 'teamA' | 'teamB';
	  }
	| {
			state: 'WAITING_FOR_ANSWER';
			teamInPlay: 'teamA' | 'teamB';
			strikes: number;
	  }
	| {
			state: 'END_OF_ROUND';
			winner: 'teamA' | 'teamB';
			pointsWon: number;
	  }
	| {
			state: 'WAITING_FOR_STEAL';
			teamInPlay: 'teamA' | 'teamB';
	  };
