/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JepState =
	| {
			state:
				| 'WAITING_FOR_CONTESTANT_INFO'
				| 'STARTING_GAME'
				| 'STARTING_NEXT_ROUND'
				| 'FINAL_JEP_AWAITING_WAGERS'
				| 'FINAL_JEP_READING_CLUE'
				| 'FINAL_JEP_AWAITING_ANSWERS'
				| 'VIEW_FINAL_RESULT';
			lastUpdated: string;
	  }
	| {
			state: 'REVEALING_CATEGORIES';
			lastRevealedCategoryIndex: number;
			lastUpdated: string;
	  }
	| {
			state: 'PICKING_CLUE';
			pickingContestantIndex: number;
			lastUpdated: string;
	  }
	| {
			state: 'READING_CLUE' | 'DAILY_DOUBLE_AWAITING_WAGER';
			lastCluePickedByIndex: number;
			cluePosition: CluePosition;
			lastUpdated: string;
	  }
	| {
			state: 'AWAITING_BUZZER';
			lastCluePickedByIndex: number;
			guessesMadeByIndices: number[];
			cluePosition: CluePosition;
			lastUpdated: string;
	  }
	| {
			state: 'DAILY_DOUBLE_READING_CLUE' | 'DAILY_DOUBLE_AWAITING_ANSWER';
			lastCluePickedByIndex: number;
			pointsWaged: number;
			cluePosition: CluePosition;
			lastUpdated: string;
	  }
	| {
			state: 'AWAITING_ANSWER';
			lastCluePickedByIndex: number;
			guessesMadeByIndices: number[];
			buzzedByIndex: number;
			cluePosition: CluePosition;
			lastUpdated: string;
	  }
	| {
			state: 'READING_CORRECT_ANSWER';
			lastCluePickedByIndex: number;
			guessesMadeByIndices: number[];
			cluePosition: CluePosition;
			lastUpdated: string;
	  }
	| {
			state: 'FINAL_JEP_REVEALING_ANSWERS';
			contestantOrderBeforeRoundStart: number[];
			answerRevealedForIndices: number[];
			lastUpdated: string;
	  };
/**
 * @minItems 2
 * @maxItems 2
 */
export type CluePosition = [number, number];
