/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 3
 * @maxItems 3
 */
export type PlayerNameplateAssignments = [
	{
		doAutomaticAssignments: boolean;
		assignments: {
			players: {
				teamId: string;
				talentId: string;
			}[];
		}[];
	},
	{
		doAutomaticAssignments: boolean;
		assignments: {
			players: {
				teamId: string;
				talentId: string;
			}[];
		}[];
	},
	{
		doAutomaticAssignments: boolean;
		assignments: {
			players: {
				teamId: string;
				talentId: string;
			}[];
		}[];
	}
];
