/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VideoFiles {
	speedruns: VideoFile[];
	interstitials: (VideoFile1 & {
		lastPlayed?: string | null;
		[k: string]: unknown;
	})[];
}
export interface VideoFile {
	name: string;
	path: string;
	type: 'LOCAL_FILE';
}
export interface VideoFile1 {
	name: string;
	path: string;
	type: 'LOCAL_FILE';
	[k: string]: unknown;
}
